security:
    acl:
        connection: default

    encoders:
        Fanta\ManagerBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: FantaManagerBundle:User, property: name }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/fantalineup
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /fantalineup/login_check
            logout:
                path:   /fantalineup/logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fantalineup, roles: ROLE_USER }