<?php

namespace Fanta\ManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FantaTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FantaTeamRepository extends EntityRepository
{
}